version: '3.8'

services:
  web:
    build: C:\Users\shia\flask-on-docker\services\web
    command: python manage.py run -h 0.0.0.0

    restart: always
    volumes:
      - C:\Users\shia\flask-on-docker\services\web\:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - C:\Users\shia\flask-on-docker\services\web\project\.env.dev